name: PNPM Lockfile Changes
on:
  - pull_request
  - workflow_dispatch

jobs:
  lockfile-changes:
    runs-on: ubuntu-24.04

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - uses: pnpm/action-setup@v6.0.8
        with:
          version: 11.5.2

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0
          cache: pnpm

      - run: pnpm ci

      - name: PNPM Lockfile Changes
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          updateComment: 'true'
